/*
 * This file is generated by jOOQ.
 */
package com.xiaowei.xxljobdemo.common;


import com.xiaowei.xxljobdemo.common.tables.User;


/**
 * Convenience access to all tables in test.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.user</code>.
     */
    public static final User USER = User.USER;
}
